name: Erlang CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        erlang: [19, 20, 21, 22]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: make compile
    - name: Elvis rock
      run: make elvis
    - name: Run xref
      run: make xref
    - name: Run eunit
      if: matrix.erlang > 20
      run: make eunit
    - name: Run dialyzer
      if: matrix.erlang > 19
      run: make dialyzer
